spring:
  datasource:
    name: vueblog  #数据库名
    url: jdbc:mysql://192.168.0.199:3306/vueblog #url链接
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.myspring.demo.entity #配置实体类
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081

myspring:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379